#!/bin/bash

# Key event listener
sxhkd &
~/.config/polybar/launch.sh

# Set wallpaper
feh --bg-fill ~/images/town2.jpg

# Make all windows floating on default
bspc rule -a "*" state=floating

# Create multiple Desktops
bspc monitor -d I II III IV V



bspc config border_width 1
bspc config window_gap 20

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config focused_border_color "#c1974c"
bspc config normal_border_color "#344443"
bspc config presel_feedback_color "#c0b18b"


xrandr --output VGA-1 --auto

# Open a new terminal
urxvt &
